// THE LEDGER - one number per pilot, and the number is how many times they
// have bent a golden rule in the open.
//
// Generated by tools/tally.sh from nothing but the git history, and checked by
// the referee: a ledger that disagrees with the history is a commit that does
// not land. Nobody edits their own record. That is the whole of it.
//
// clean is the other half of the arithmetic: versions the pilot has landed
// since their last bend, read off the same history. Three of them ease the
// field by one bend's worth - src/game/tally.js does that sum. See GR12.
//
// What the number does to a pilot's field is in src/game/tally.js. See GR12.
ASTEROIDS.LEDGER = {
  "David Friedrich": { bends: 5, clean: 16, last: "GR6" },
};
