// THE LEDGER - one number per pilot, and the number is how many times they
// have bent a golden rule in the open.
//
// Generated by tools/tally.sh from nothing but the git history, and checked by
// the referee: a ledger that disagrees with the history is a commit that does
// not land. Nobody edits their own record. That is the whole of it.
//
// What the number does to a pilot's field is in src/game/tally.js. See GR12.
ASTEROIDS.LEDGER = {
  "David Friedrich": { bends: 5, last: "GR6" },
};
